// COMPLETE FiveM control catalogue — every control listed in the official docs
// at https://docs.fivem.net/docs/game-references/controls/ (indices 0–360, ~349
// entries). Auto-expanded from the docs' raw table; the hand-written labels and
// group assignments from the previous curated subset are preserved (matched by
// symbol), and every id / default key here is taken from the docs source of truth.
// These are the IsControlPressed / DisableControlAction numeric IDs.

export type GtaControl = {
  /** Numeric control ID passed to IsControlPressed / EnableControlAction. */
  id: number;
  /** Symbolic name as it appears in the FiveM docs (e.g. INPUT_LOOK_LR). */
  symbol: string;
  /** Friendly label suitable for UI display (e.g. "Look Left/Right"). */
  label: string;
  /** Default keyboard binding shown for context (e.g. "Mouse X", "E"). */
  defaultKey?: string;
  /** Group used for ordering and section headers in pickers. */
  group: GtaControlGroup;
};

export type GtaControlGroup =
  | "Camera"
  | "Movement"
  | "Combat"
  | "Cover"
  | "Vehicle"
  | "Vehicle (Plane/Heli)"
  | "Vehicle (Boat/Bike)"
  | "Phone"
  | "Frontend / UI"
  | "Multiplayer"
  | "Misc";

export const GTA_CONTROLS: GtaControl[] = [
  // ── Camera ─────────────────────────────────────────────────────────────────
  { id: 0,   symbol: "INPUT_NEXT_CAMERA",                           label: "Switch Camera",                  defaultKey: "V",           group: "Camera" },
  { id: 1,   symbol: "INPUT_LOOK_LR",                               label: "Look Left/Right",                defaultKey: "Mouse X",     group: "Camera" },
  { id: 2,   symbol: "INPUT_LOOK_UD",                               label: "Look Up/Down",                   defaultKey: "Mouse Y",     group: "Camera" },
  { id: 3,   symbol: "INPUT_LOOK_UP_ONLY",                          label: "Look Up Only",                                              group: "Camera" },
  { id: 4,   symbol: "INPUT_LOOK_DOWN_ONLY",                        label: "Look Down Only",                 defaultKey: "Mouse Y",     group: "Camera" },
  { id: 5,   symbol: "INPUT_LOOK_LEFT_ONLY",                        label: "Look Left Only",                                            group: "Camera" },
  { id: 6,   symbol: "INPUT_LOOK_RIGHT_ONLY",                       label: "Look Right Only",                defaultKey: "Mouse X",     group: "Camera" },
  { id: 7,   symbol: "INPUT_CINEMATIC_SLOWMO",                      label: "Cinematic Slowmo",                                          group: "Camera" },
  { id: 26,  symbol: "INPUT_LOOK_BEHIND",                           label: "Look Behind",                    defaultKey: "C",           group: "Camera" },
  { id: 95,  symbol: "INPUT_VEH_CINEMATIC_UD",                      label: "Veh Cinematic UD",               defaultKey: "Mouse Y",     group: "Camera" },
  { id: 96,  symbol: "INPUT_VEH_CINEMATIC_UP_ONLY",                 label: "Veh Cinematic Up Only",          defaultKey: "Numpad -",    group: "Camera" },
  { id: 97,  symbol: "INPUT_VEH_CINEMATIC_DOWN_ONLY",               label: "Veh Cinematic Down Only",        defaultKey: "Numpad +",    group: "Camera" },
  { id: 98,  symbol: "INPUT_VEH_CINEMATIC_LR",                      label: "Veh Cinematic LR",               defaultKey: "Mouse X",     group: "Camera" },
  { id: 121, symbol: "INPUT_VEH_FLY_ATTACK_CAMERA",                 label: "Veh Fly Attack Camera",          defaultKey: "Insert",      group: "Camera" },
  { id: 182, symbol: "INPUT_CELLPHONE_CAMERA_FOCUS_LOCK",           label: "Cellphone Camera Focus Lock",    defaultKey: "L",           group: "Camera" },
  { id: 183, symbol: "INPUT_CELLPHONE_CAMERA_GRID",                 label: "Cellphone Camera Grid",          defaultKey: "G",           group: "Camera" },
  { id: 184, symbol: "INPUT_CELLPHONE_CAMERA_SELFIE",               label: "Cellphone Camera Selfie",        defaultKey: "E",           group: "Camera" },
  { id: 185, symbol: "INPUT_CELLPHONE_CAMERA_DOF",                  label: "Cellphone Camera Dof",           defaultKey: "F",           group: "Camera" },
  { id: 186, symbol: "INPUT_CELLPHONE_CAMERA_EXPRESSION",           label: "Cellphone Camera Expression",    defaultKey: "X",           group: "Camera" },
  { id: 270, symbol: "INPUT_LOOK_LEFT",                             label: "Look Left",                      defaultKey: "Mouse X",     group: "Camera" },
  { id: 271, symbol: "INPUT_LOOK_RIGHT",                            label: "Look Right",                     defaultKey: "Mouse X",     group: "Camera" },
  { id: 272, symbol: "INPUT_LOOK_UP",                               label: "Look Up",                        defaultKey: "Mouse Y",     group: "Camera" },
  { id: 273, symbol: "INPUT_LOOK_DOWN",                             label: "Look Down",                      defaultKey: "Mouse Y",     group: "Camera" },
  { id: 316, symbol: "INPUT_REPLAY_CAMERAUP",                       label: "Replay Cameraup",                defaultKey: "Page Up",     group: "Camera" },
  { id: 317, symbol: "INPUT_REPLAY_CAMERADOWN",                     label: "Replay Cameradown",              defaultKey: "Page Down",   group: "Camera" },

  // ── Movement ───────────────────────────────────────────────────────────────
  { id: 21,  symbol: "INPUT_SPRINT",                                label: "Sprint",                         defaultKey: "Left Shift",  group: "Movement" },
  { id: 22,  symbol: "INPUT_JUMP",                                  label: "Jump",                           defaultKey: "Space",       group: "Movement" },
  { id: 23,  symbol: "INPUT_ENTER",                                 label: "Enter Vehicle",                  defaultKey: "F",           group: "Movement" },
  { id: 30,  symbol: "INPUT_MOVE_LR",                               label: "Move Left/Right",                defaultKey: "D",           group: "Movement" },
  { id: 31,  symbol: "INPUT_MOVE_UD",                               label: "Move Up/Down",                   defaultKey: "S",           group: "Movement" },
  { id: 32,  symbol: "INPUT_MOVE_UP_ONLY",                          label: "Move Forward (W)",               defaultKey: "W",           group: "Movement" },
  { id: 33,  symbol: "INPUT_MOVE_DOWN_ONLY",                        label: "Move Back (S)",                  defaultKey: "S",           group: "Movement" },
  { id: 34,  symbol: "INPUT_MOVE_LEFT_ONLY",                        label: "Move Left (A)",                  defaultKey: "A",           group: "Movement" },
  { id: 35,  symbol: "INPUT_MOVE_RIGHT_ONLY",                       label: "Move Right (D)",                 defaultKey: "D",           group: "Movement" },
  { id: 36,  symbol: "INPUT_DUCK",                                  label: "Duck / Stealth",                 defaultKey: "Left Ctrl",   group: "Movement" },
  { id: 38,  symbol: "INPUT_PICKUP",                                label: "Pickup / Interact",              defaultKey: "E",           group: "Movement" },
  { id: 266, symbol: "INPUT_MOVE_LEFT",                             label: "Move Left",                      defaultKey: "D",           group: "Movement" },
  { id: 267, symbol: "INPUT_MOVE_RIGHT",                            label: "Move Right",                     defaultKey: "D",           group: "Movement" },
  { id: 268, symbol: "INPUT_MOVE_UP",                               label: "Move Up",                        defaultKey: "S",           group: "Movement" },
  { id: 269, symbol: "INPUT_MOVE_DOWN",                             label: "Move Down",                      defaultKey: "S",           group: "Movement" },

  // ── Combat ─────────────────────────────────────────────────────────────────
  { id: 12,  symbol: "INPUT_WEAPON_WHEEL_UD",                       label: "Weapon Wheel UD",                defaultKey: "Mouse Y",     group: "Combat" },
  { id: 13,  symbol: "INPUT_WEAPON_WHEEL_LR",                       label: "Weapon Wheel LR",                defaultKey: "Mouse X",     group: "Combat" },
  { id: 14,  symbol: "INPUT_WEAPON_WHEEL_NEXT",                     label: "Weapon Wheel Next",              defaultKey: "Scroll Down", group: "Combat" },
  { id: 15,  symbol: "INPUT_WEAPON_WHEEL_PREV",                     label: "Weapon Wheel Prev",              defaultKey: "Scroll Up",   group: "Combat" },
  { id: 24,  symbol: "INPUT_ATTACK",                                label: "Attack / Fire",                  defaultKey: "Mouse 1",     group: "Combat" },
  { id: 25,  symbol: "INPUT_AIM",                                   label: "Aim",                            defaultKey: "Mouse 2",     group: "Combat" },
  { id: 37,  symbol: "INPUT_SELECT_WEAPON",                         label: "Weapon Wheel",                   defaultKey: "Tab",         group: "Combat" },
  { id: 45,  symbol: "INPUT_RELOAD",                                label: "Reload",                         defaultKey: "R",           group: "Combat" },
  { id: 47,  symbol: "INPUT_DETONATE",                              label: "Detonate",                       defaultKey: "G",           group: "Combat" },
  { id: 53,  symbol: "INPUT_WEAPON_SPECIAL",                        label: "Weapon Special",                                            group: "Combat" },
  { id: 54,  symbol: "INPUT_WEAPON_SPECIAL_TWO",                    label: "Weapon Special Two",             defaultKey: "E",           group: "Combat" },
  { id: 58,  symbol: "INPUT_THROW_GRENADE",                         label: "Throw Grenade",                  defaultKey: "G",           group: "Combat" },
  { id: 140, symbol: "INPUT_MELEE_ATTACK_LIGHT",                    label: "Melee Light",                    defaultKey: "R",           group: "Combat" },
  { id: 141, symbol: "INPUT_MELEE_ATTACK_HEAVY",                    label: "Melee Heavy",                    defaultKey: "Q",           group: "Combat" },
  { id: 142, symbol: "INPUT_MELEE_ATTACK_ALTERNATE",                label: "Melee Alternate",                defaultKey: "Mouse 1",     group: "Combat" },
  { id: 143, symbol: "INPUT_MELEE_BLOCK",                           label: "Melee Block",                    defaultKey: "Space",       group: "Combat" },
  { id: 157, symbol: "INPUT_SELECT_WEAPON_UNARMED",                 label: "Select Weapon Unarmed",          defaultKey: "1",           group: "Combat" },
  { id: 158, symbol: "INPUT_SELECT_WEAPON_MELEE",                   label: "Select Weapon Melee",            defaultKey: "2",           group: "Combat" },
  { id: 159, symbol: "INPUT_SELECT_WEAPON_HANDGUN",                 label: "Select Weapon Handgun",          defaultKey: "6",           group: "Combat" },
  { id: 160, symbol: "INPUT_SELECT_WEAPON_SHOTGUN",                 label: "Select Weapon Shotgun",          defaultKey: "3",           group: "Combat" },
  { id: 161, symbol: "INPUT_SELECT_WEAPON_SMG",                     label: "Select Weapon Smg",              defaultKey: "7",           group: "Combat" },
  { id: 162, symbol: "INPUT_SELECT_WEAPON_AUTO_RIFLE",              label: "Select Weapon Auto Rifle",       defaultKey: "8",           group: "Combat" },
  { id: 163, symbol: "INPUT_SELECT_WEAPON_SNIPER",                  label: "Select Weapon Sniper",           defaultKey: "9",           group: "Combat" },
  { id: 164, symbol: "INPUT_SELECT_WEAPON_HEAVY",                   label: "Select Weapon Heavy",            defaultKey: "4",           group: "Combat" },
  { id: 165, symbol: "INPUT_SELECT_WEAPON_SPECIAL",                 label: "Select Weapon Special",          defaultKey: "5",           group: "Combat" },
  { id: 257, symbol: "INPUT_ATTACK2",                               label: "Attack 2",                       defaultKey: "Mouse 1",     group: "Combat" },
  { id: 263, symbol: "INPUT_MELEE_ATTACK1",                         label: "Melee Attack 1",                 defaultKey: "R",           group: "Combat" },
  { id: 264, symbol: "INPUT_MELEE_ATTACK2",                         label: "Melee Attack 2",                 defaultKey: "Q",           group: "Combat" },

  // ── Cover ──────────────────────────────────────────────────────────────────
  { id: 44,  symbol: "INPUT_COVER",                                 label: "Cover",                          defaultKey: "Q",           group: "Cover" },

  // ── Vehicle ────────────────────────────────────────────────────────────────
  { id: 59,  symbol: "INPUT_VEH_MOVE_LR",                           label: "Vehicle Steering",               defaultKey: "D",           group: "Vehicle" },
  { id: 60,  symbol: "INPUT_VEH_MOVE_UD",                           label: "Veh Move UD",                    defaultKey: "Left Ctrl",   group: "Vehicle" },
  { id: 61,  symbol: "INPUT_VEH_MOVE_UP_ONLY",                      label: "Veh Move Up Only",               defaultKey: "Left Shift",  group: "Vehicle" },
  { id: 62,  symbol: "INPUT_VEH_MOVE_DOWN_ONLY",                    label: "Veh Move Down Only",             defaultKey: "Left Ctrl",   group: "Vehicle" },
  { id: 63,  symbol: "INPUT_VEH_MOVE_LEFT_ONLY",                    label: "Vehicle Steer Left",             defaultKey: "A",           group: "Vehicle" },
  { id: 64,  symbol: "INPUT_VEH_MOVE_RIGHT_ONLY",                   label: "Vehicle Steer Right",            defaultKey: "D",           group: "Vehicle" },
  { id: 65,  symbol: "INPUT_VEH_SPECIAL",                           label: "Veh Special",                                               group: "Vehicle" },
  { id: 66,  symbol: "INPUT_VEH_GUN_LR",                            label: "Veh Gun LR",                     defaultKey: "Mouse X",     group: "Vehicle" },
  { id: 67,  symbol: "INPUT_VEH_GUN_UD",                            label: "Veh Gun UD",                     defaultKey: "Mouse Y",     group: "Vehicle" },
  { id: 68,  symbol: "INPUT_VEH_AIM",                               label: "Vehicle Aim",                    defaultKey: "Mouse 2",     group: "Vehicle" },
  { id: 69,  symbol: "INPUT_VEH_ATTACK",                            label: "Vehicle Attack",                 defaultKey: "Mouse 1",     group: "Vehicle" },
  { id: 70,  symbol: "INPUT_VEH_ATTACK2",                           label: "Vehicle Attack 2",               defaultKey: "Mouse 2",     group: "Vehicle" },
  { id: 71,  symbol: "INPUT_VEH_ACCELERATE",                        label: "Vehicle Accelerate",             defaultKey: "W",           group: "Vehicle" },
  { id: 72,  symbol: "INPUT_VEH_BRAKE",                             label: "Vehicle Brake",                  defaultKey: "S",           group: "Vehicle" },
  { id: 73,  symbol: "INPUT_VEH_DUCK",                              label: "Vehicle Duck",                   defaultKey: "X",           group: "Vehicle" },
  { id: 74,  symbol: "INPUT_VEH_HEADLIGHT",                         label: "Headlights",                     defaultKey: "H",           group: "Vehicle" },
  { id: 75,  symbol: "INPUT_VEH_EXIT",                              label: "Exit Vehicle",                   defaultKey: "F",           group: "Vehicle" },
  { id: 76,  symbol: "INPUT_VEH_HANDBRAKE",                         label: "Handbrake",                      defaultKey: "Space",       group: "Vehicle" },
  { id: 77,  symbol: "INPUT_VEH_HOTWIRE_LEFT",                      label: "Veh Hotwire Left",               defaultKey: "W",           group: "Vehicle" },
  { id: 78,  symbol: "INPUT_VEH_HOTWIRE_RIGHT",                     label: "Veh Hotwire Right",              defaultKey: "S",           group: "Vehicle" },
  { id: 79,  symbol: "INPUT_VEH_LOOK_BEHIND",                       label: "Veh Look Behind",                defaultKey: "C",           group: "Vehicle" },
  { id: 80,  symbol: "INPUT_VEH_CIN_CAM",                           label: "Cinematic Cam",                  defaultKey: "R",           group: "Vehicle" },
  { id: 81,  symbol: "INPUT_VEH_NEXT_RADIO",                        label: "Radio Next",                     defaultKey: ".",           group: "Vehicle" },
  { id: 82,  symbol: "INPUT_VEH_PREV_RADIO",                        label: "Radio Prev",                     defaultKey: ",",           group: "Vehicle" },
  { id: 83,  symbol: "INPUT_VEH_NEXT_RADIO_TRACK",                  label: "Radio Next Track",               defaultKey: "=",           group: "Vehicle" },
  { id: 84,  symbol: "INPUT_VEH_PREV_RADIO_TRACK",                  label: "Radio Prev Track",               defaultKey: "-",           group: "Vehicle" },
  { id: 85,  symbol: "INPUT_VEH_RADIO_WHEEL",                       label: "Radio Wheel",                    defaultKey: "Q",           group: "Vehicle" },
  { id: 86,  symbol: "INPUT_VEH_HORN",                              label: "Horn",                           defaultKey: "E",           group: "Vehicle" },
  { id: 91,  symbol: "INPUT_VEH_PASSENGER_AIM",                     label: "Veh Passenger Aim",              defaultKey: "Mouse 2",     group: "Vehicle" },
  { id: 92,  symbol: "INPUT_VEH_PASSENGER_ATTACK",                  label: "Veh Passenger Attack",           defaultKey: "Mouse 1",     group: "Vehicle" },
  { id: 93,  symbol: "INPUT_VEH_SPECIAL_ABILITY_FRANKLIN",          label: "Veh Special Ability Franklin",                              group: "Vehicle" },
  { id: 94,  symbol: "INPUT_VEH_STUNT_UD",                          label: "Veh Stunt UD",                                              group: "Vehicle" },
  { id: 99,  symbol: "INPUT_VEH_SELECT_NEXT_WEAPON",                label: "Veh Next Weapon",                defaultKey: "Scroll Up",   group: "Vehicle" },
  { id: 100, symbol: "INPUT_VEH_SELECT_PREV_WEAPON",                label: "Veh Prev Weapon",                defaultKey: "[",           group: "Vehicle" },
  { id: 101, symbol: "INPUT_VEH_ROOF",                              label: "Veh Roof",                       defaultKey: "H",           group: "Vehicle" },
  { id: 102, symbol: "INPUT_VEH_JUMP",                              label: "Veh Jump",                       defaultKey: "Space",       group: "Vehicle" },
  { id: 103, symbol: "INPUT_VEH_GRAPPLING_HOOK",                    label: "Veh Grappling Hook",             defaultKey: "E",           group: "Vehicle" },
  { id: 104, symbol: "INPUT_VEH_SHUFFLE",                           label: "Veh Shuffle",                    defaultKey: "H",           group: "Vehicle" },
  { id: 105, symbol: "INPUT_VEH_DROP_PROJECTILE",                   label: "Veh Drop Projectile",            defaultKey: "X",           group: "Vehicle" },
  { id: 106, symbol: "INPUT_VEH_MOUSE_CONTROL_OVERRIDE",            label: "Veh Mouse Control Override",     defaultKey: "Mouse 1",     group: "Vehicle" },
  { id: 278, symbol: "INPUT_VEH_MOVE_LEFT",                         label: "Veh Move Left",                  defaultKey: "D",           group: "Vehicle" },
  { id: 279, symbol: "INPUT_VEH_MOVE_RIGHT",                        label: "Veh Move Right",                 defaultKey: "D",           group: "Vehicle" },
  { id: 280, symbol: "INPUT_VEH_MOVE_UP",                           label: "Veh Move Up",                    defaultKey: "Left Ctrl",   group: "Vehicle" },
  { id: 281, symbol: "INPUT_VEH_MOVE_DOWN",                         label: "Veh Move Down",                  defaultKey: "Left Ctrl",   group: "Vehicle" },
  { id: 282, symbol: "INPUT_VEH_GUN_LEFT",                          label: "Veh Gun Left",                   defaultKey: "Mouse X",     group: "Vehicle" },
  { id: 283, symbol: "INPUT_VEH_GUN_RIGHT",                         label: "Veh Gun Right",                  defaultKey: "Mouse X",     group: "Vehicle" },
  { id: 284, symbol: "INPUT_VEH_GUN_UP",                            label: "Veh Gun Up",                     defaultKey: "Mouse X",     group: "Vehicle" },
  { id: 285, symbol: "INPUT_VEH_GUN_DOWN",                          label: "Veh Gun Down",                   defaultKey: "Mouse X",     group: "Vehicle" },
  { id: 286, symbol: "INPUT_VEH_LOOK_LEFT",                         label: "Veh Look Left",                  defaultKey: "Mouse X",     group: "Vehicle" },
  { id: 287, symbol: "INPUT_VEH_LOOK_RIGHT",                        label: "Veh Look Right",                 defaultKey: "Mouse X",     group: "Vehicle" },
  { id: 329, symbol: "INPUT_VEH_DRIVE_LOOK",                        label: "Veh Drive Look",                 defaultKey: "Mouse 1",     group: "Vehicle" },
  { id: 330, symbol: "INPUT_VEH_DRIVE_LOOK2",                       label: "Veh Drive Look2",                defaultKey: "Mouse 2",     group: "Vehicle" },
  { id: 334, symbol: "INPUT_VEH_SLOWMO_UD",                         label: "Veh Slowmo UD",                  defaultKey: "Scroll Down", group: "Vehicle" },
  { id: 335, symbol: "INPUT_VEH_SLOWMO_UP_ONLY",                    label: "Veh Slowmo Up Only",             defaultKey: "Scroll Up",   group: "Vehicle" },
  { id: 336, symbol: "INPUT_VEH_SLOWMO_DOWN_ONLY",                  label: "Veh Slowmo Down Only",           defaultKey: "Scroll Down", group: "Vehicle" },
  { id: 337, symbol: "INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE",         label: "Veh Hydraulics Control Toggle",  defaultKey: "X",           group: "Vehicle" },
  { id: 338, symbol: "INPUT_VEH_HYDRAULICS_CONTROL_LEFT",           label: "Veh Hydraulics Control Left",    defaultKey: "A",           group: "Vehicle" },
  { id: 339, symbol: "INPUT_VEH_HYDRAULICS_CONTROL_RIGHT",          label: "Veh Hydraulics Control Right",   defaultKey: "D",           group: "Vehicle" },
  { id: 340, symbol: "INPUT_VEH_HYDRAULICS_CONTROL_UP",             label: "Veh Hydraulics Control Up",      defaultKey: "Left Shift",  group: "Vehicle" },
  { id: 341, symbol: "INPUT_VEH_HYDRAULICS_CONTROL_DOWN",           label: "Veh Hydraulics Control Down",    defaultKey: "Left Ctrl",   group: "Vehicle" },
  { id: 342, symbol: "INPUT_VEH_HYDRAULICS_CONTROL_UD",             label: "Veh Hydraulics Control UD",      defaultKey: "D",           group: "Vehicle" },
  { id: 343, symbol: "INPUT_VEH_HYDRAULICS_CONTROL_LR",             label: "Veh Hydraulics Control LR",      defaultKey: "Left Ctrl",   group: "Vehicle" },
  { id: 345, symbol: "INPUT_VEH_MELEE_HOLD",                        label: "Veh Melee Hold",                 defaultKey: "X",           group: "Vehicle" },
  { id: 346, symbol: "INPUT_VEH_MELEE_LEFT",                        label: "Veh Melee Left",                 defaultKey: "Mouse 1",     group: "Vehicle" },
  { id: 347, symbol: "INPUT_VEH_MELEE_RIGHT",                       label: "Veh Melee Right",                defaultKey: "Mouse 2",     group: "Vehicle" },
  { id: 350, symbol: "INPUT_VEH_CAR_JUMP",                          label: "Veh Car Jump",                   defaultKey: "E",           group: "Vehicle" },
  { id: 351, symbol: "INPUT_VEH_ROCKET_BOOST",                      label: "Veh Rocket Boost",               defaultKey: "E",           group: "Vehicle" },
  { id: 353, symbol: "INPUT_VEH_PARACHUTE",                         label: "Veh Parachute",                  defaultKey: "Space",       group: "Vehicle" },
  { id: 354, symbol: "INPUT_VEH_BIKE_WINGS",                        label: "Veh Bike Wings",                 defaultKey: "X",           group: "Vehicle" },
  { id: 357, symbol: "INPUT_VEH_TRANSFORM",                         label: "Veh Transform",                  defaultKey: "X",           group: "Vehicle" },

  // ── Vehicle (Plane/Heli) ───────────────────────────────────────────────────
  { id: 87,  symbol: "INPUT_VEH_FLY_THROTTLE_UP",                   label: "Plane Throttle Up",              defaultKey: "W",           group: "Vehicle (Plane/Heli)" },
  { id: 88,  symbol: "INPUT_VEH_FLY_THROTTLE_DOWN",                 label: "Plane Throttle Down",            defaultKey: "S",           group: "Vehicle (Plane/Heli)" },
  { id: 89,  symbol: "INPUT_VEH_FLY_YAW_LEFT",                      label: "Plane Yaw Left",                 defaultKey: "A",           group: "Vehicle (Plane/Heli)" },
  { id: 90,  symbol: "INPUT_VEH_FLY_YAW_RIGHT",                     label: "Plane Yaw Right",                defaultKey: "D",           group: "Vehicle (Plane/Heli)" },
  { id: 107, symbol: "INPUT_VEH_FLY_ROLL_LR",                       label: "Veh Fly Roll LR",                defaultKey: "Numpad 6",    group: "Vehicle (Plane/Heli)" },
  { id: 108, symbol: "INPUT_VEH_FLY_ROLL_LEFT_ONLY",                label: "Veh Fly Roll Left Only",         defaultKey: "Numpad 4",    group: "Vehicle (Plane/Heli)" },
  { id: 109, symbol: "INPUT_VEH_FLY_ROLL_RIGHT_ONLY",               label: "Veh Fly Roll Right Only",        defaultKey: "Numpad 6",    group: "Vehicle (Plane/Heli)" },
  { id: 110, symbol: "INPUT_VEH_FLY_PITCH_UD",                      label: "Veh Fly Pitch UD",               defaultKey: "Numpad 5",    group: "Vehicle (Plane/Heli)" },
  { id: 111, symbol: "INPUT_VEH_FLY_PITCH_UP_ONLY",                 label: "Veh Fly Pitch Up Only",          defaultKey: "Numpad 8",    group: "Vehicle (Plane/Heli)" },
  { id: 112, symbol: "INPUT_VEH_FLY_PITCH_DOWN_ONLY",               label: "Veh Fly Pitch Down Only",        defaultKey: "Numpad 5",    group: "Vehicle (Plane/Heli)" },
  { id: 113, symbol: "INPUT_VEH_FLY_UNDERCARRIAGE",                 label: "Veh Fly Undercarriage",          defaultKey: "G",           group: "Vehicle (Plane/Heli)" },
  { id: 114, symbol: "INPUT_VEH_FLY_ATTACK",                        label: "Plane Attack",                   defaultKey: "Mouse 2",     group: "Vehicle (Plane/Heli)" },
  { id: 115, symbol: "INPUT_VEH_FLY_SELECT_NEXT_WEAPON",            label: "Veh Fly Select Next Weapon",     defaultKey: "Scroll Up",   group: "Vehicle (Plane/Heli)" },
  { id: 116, symbol: "INPUT_VEH_FLY_SELECT_PREV_WEAPON",            label: "Veh Fly Select Prev Weapon",     defaultKey: "[",           group: "Vehicle (Plane/Heli)" },
  { id: 117, symbol: "INPUT_VEH_FLY_SELECT_TARGET_LEFT",            label: "Veh Fly Select Target Left",     defaultKey: "Numpad 7",    group: "Vehicle (Plane/Heli)" },
  { id: 118, symbol: "INPUT_VEH_FLY_SELECT_TARGET_RIGHT",           label: "Veh Fly Select Target Right",    defaultKey: "Numpad 9",    group: "Vehicle (Plane/Heli)" },
  { id: 119, symbol: "INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE",          label: "Veh Fly Vertical Flight Mode",   defaultKey: "E",           group: "Vehicle (Plane/Heli)" },
  { id: 120, symbol: "INPUT_VEH_FLY_DUCK",                          label: "Veh Fly Duck",                   defaultKey: "X",           group: "Vehicle (Plane/Heli)" },
  { id: 122, symbol: "INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE",        label: "Veh Fly Mouse Control Override", defaultKey: "Mouse 1",     group: "Vehicle (Plane/Heli)" },
  { id: 331, symbol: "INPUT_VEH_FLY_ATTACK2",                       label: "Veh Fly Attack2",                defaultKey: "Mouse 2",     group: "Vehicle (Plane/Heli)" },
  { id: 352, symbol: "INPUT_VEH_FLY_BOOST",                         label: "Veh Fly Boost",                  defaultKey: "Left Shift",  group: "Vehicle (Plane/Heli)" },
  { id: 355, symbol: "INPUT_VEH_FLY_BOMB_BAY",                      label: "Veh Fly Bomb Bay",               defaultKey: "E",           group: "Vehicle (Plane/Heli)" },
  { id: 356, symbol: "INPUT_VEH_FLY_COUNTER",                       label: "Veh Fly Counter",                defaultKey: "E",           group: "Vehicle (Plane/Heli)" },

  // ── Vehicle (Boat/Bike) ────────────────────────────────────────────────────
  { id: 123, symbol: "INPUT_VEH_SUB_TURN_LR",                       label: "Veh Sub Turn LR",                defaultKey: "Numpad 6",    group: "Vehicle (Boat/Bike)" },
  { id: 124, symbol: "INPUT_VEH_SUB_TURN_LEFT_ONLY",                label: "Veh Sub Turn Left Only",         defaultKey: "Numpad 4",    group: "Vehicle (Boat/Bike)" },
  { id: 125, symbol: "INPUT_VEH_SUB_TURN_RIGHT_ONLY",               label: "Veh Sub Turn Right Only",        defaultKey: "Numpad 6",    group: "Vehicle (Boat/Bike)" },
  { id: 126, symbol: "INPUT_VEH_SUB_PITCH_UD",                      label: "Veh Sub Pitch UD",               defaultKey: "Numpad 5",    group: "Vehicle (Boat/Bike)" },
  { id: 127, symbol: "INPUT_VEH_SUB_PITCH_UP_ONLY",                 label: "Veh Sub Pitch Up Only",          defaultKey: "Numpad 8",    group: "Vehicle (Boat/Bike)" },
  { id: 128, symbol: "INPUT_VEH_SUB_PITCH_DOWN_ONLY",               label: "Veh Sub Pitch Down Only",        defaultKey: "Numpad 5",    group: "Vehicle (Boat/Bike)" },
  { id: 129, symbol: "INPUT_VEH_SUB_THROTTLE_UP",                   label: "Veh Sub Throttle Up",            defaultKey: "W",           group: "Vehicle (Boat/Bike)" },
  { id: 130, symbol: "INPUT_VEH_SUB_THROTTLE_DOWN",                 label: "Veh Sub Throttle Down",          defaultKey: "S",           group: "Vehicle (Boat/Bike)" },
  { id: 131, symbol: "INPUT_VEH_SUB_ASCEND",                        label: "Veh Sub Ascend",                 defaultKey: "Left Shift",  group: "Vehicle (Boat/Bike)" },
  { id: 132, symbol: "INPUT_VEH_SUB_DESCEND",                       label: "Veh Sub Descend",                defaultKey: "Left Ctrl",   group: "Vehicle (Boat/Bike)" },
  { id: 133, symbol: "INPUT_VEH_SUB_TURN_HARD_LEFT",                label: "Veh Sub Turn Hard Left",         defaultKey: "A",           group: "Vehicle (Boat/Bike)" },
  { id: 134, symbol: "INPUT_VEH_SUB_TURN_HARD_RIGHT",               label: "Veh Sub Turn Hard Right",        defaultKey: "D",           group: "Vehicle (Boat/Bike)" },
  { id: 135, symbol: "INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE",        label: "Veh Sub Mouse Control Override", defaultKey: "Mouse 1",     group: "Vehicle (Boat/Bike)" },
  { id: 136, symbol: "INPUT_VEH_PUSHBIKE_PEDAL",                    label: "Veh Pushbike Pedal",             defaultKey: "W",           group: "Vehicle (Boat/Bike)" },
  { id: 137, symbol: "INPUT_VEH_PUSHBIKE_SPRINT",                   label: "Veh Pushbike Sprint",            defaultKey: "Caps Lock",   group: "Vehicle (Boat/Bike)" },
  { id: 138, symbol: "INPUT_VEH_PUSHBIKE_FRONT_BRAKE",              label: "Veh Pushbike Front Brake",       defaultKey: "Q",           group: "Vehicle (Boat/Bike)" },
  { id: 139, symbol: "INPUT_VEH_PUSHBIKE_REAR_BRAKE",               label: "Veh Pushbike Rear Brake",        defaultKey: "S",           group: "Vehicle (Boat/Bike)" },

  // ── Phone ──────────────────────────────────────────────────────────────────
  { id: 27,  symbol: "INPUT_PHONE",                                 label: "Phone",                          defaultKey: "Up Arrow",    group: "Phone" },
  { id: 172, symbol: "INPUT_CELLPHONE_UP",                          label: "Cellphone Up",                   defaultKey: "Up Arrow",    group: "Phone" },
  { id: 173, symbol: "INPUT_CELLPHONE_DOWN",                        label: "Cellphone Down",                 defaultKey: "Down Arrow",  group: "Phone" },
  { id: 174, symbol: "INPUT_CELLPHONE_LEFT",                        label: "Cellphone Left",                 defaultKey: "Left Arrow",  group: "Phone" },
  { id: 175, symbol: "INPUT_CELLPHONE_RIGHT",                       label: "Cellphone Right",                defaultKey: "Right Arrow", group: "Phone" },
  { id: 176, symbol: "INPUT_CELLPHONE_SELECT",                      label: "Cellphone Select",               defaultKey: "Enter",       group: "Phone" },
  { id: 177, symbol: "INPUT_CELLPHONE_CANCEL",                      label: "Cellphone Cancel",               defaultKey: "Backspace",   group: "Phone" },
  { id: 178, symbol: "INPUT_CELLPHONE_OPTION",                      label: "Cellphone Option",               defaultKey: "Delete",      group: "Phone" },
  { id: 179, symbol: "INPUT_CELLPHONE_EXTRA_OPTION",                label: "Cellphone Extra Option",         defaultKey: "Space",       group: "Phone" },
  { id: 180, symbol: "INPUT_CELLPHONE_SCROLL_FORWARD",              label: "Cellphone Scroll Forward",       defaultKey: "Scroll Down", group: "Phone" },
  { id: 181, symbol: "INPUT_CELLPHONE_SCROLL_BACKWARD",             label: "Cellphone Scroll Backward",      defaultKey: "Scroll Up",   group: "Phone" },
  { id: 213, symbol: "INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY",        label: "Toggle Phone (alt)",             defaultKey: "Home",        group: "Phone" },

  // ── Frontend / UI ──────────────────────────────────────────────────────────
  { id: 187, symbol: "INPUT_FRONTEND_DOWN",                         label: "Frontend Down",                  defaultKey: "Down Arrow",  group: "Frontend / UI" },
  { id: 188, symbol: "INPUT_FRONTEND_UP",                           label: "Frontend Up",                    defaultKey: "Up Arrow",    group: "Frontend / UI" },
  { id: 189, symbol: "INPUT_FRONTEND_LEFT",                         label: "Frontend Left",                  defaultKey: "Left Arrow",  group: "Frontend / UI" },
  { id: 190, symbol: "INPUT_FRONTEND_RIGHT",                        label: "Frontend Right",                 defaultKey: "Right Arrow", group: "Frontend / UI" },
  { id: 191, symbol: "INPUT_FRONTEND_RDOWN",                        label: "Frontend Rdown",                 defaultKey: "Enter",       group: "Frontend / UI" },
  { id: 192, symbol: "INPUT_FRONTEND_RUP",                          label: "Frontend Rup",                   defaultKey: "Tab",         group: "Frontend / UI" },
  { id: 193, symbol: "INPUT_FRONTEND_RLEFT",                        label: "Frontend Rleft",                                            group: "Frontend / UI" },
  { id: 194, symbol: "INPUT_FRONTEND_RRIGHT",                       label: "Frontend Rright",                defaultKey: "Backspace",   group: "Frontend / UI" },
  { id: 195, symbol: "INPUT_FRONTEND_AXIS_X",                       label: "Frontend Axis X",                defaultKey: "D",           group: "Frontend / UI" },
  { id: 196, symbol: "INPUT_FRONTEND_AXIS_Y",                       label: "Frontend Axis Y",                defaultKey: "S",           group: "Frontend / UI" },
  { id: 197, symbol: "INPUT_FRONTEND_RIGHT_AXIS_X",                 label: "Frontend Right Axis X",          defaultKey: "]",           group: "Frontend / UI" },
  { id: 198, symbol: "INPUT_FRONTEND_RIGHT_AXIS_Y",                 label: "Frontend Right Axis Y",          defaultKey: "Scroll Down", group: "Frontend / UI" },
  { id: 199, symbol: "INPUT_FRONTEND_PAUSE",                        label: "Pause Menu",                     defaultKey: "P",           group: "Frontend / UI" },
  { id: 200, symbol: "INPUT_FRONTEND_PAUSE_ALTERNATE",              label: "Pause Menu (alt)",               defaultKey: "Esc",         group: "Frontend / UI" },
  { id: 201, symbol: "INPUT_FRONTEND_ACCEPT",                       label: "Accept",                         defaultKey: "Enter",       group: "Frontend / UI" },
  { id: 202, symbol: "INPUT_FRONTEND_CANCEL",                       label: "Cancel",                         defaultKey: "Backspace",   group: "Frontend / UI" },
  { id: 203, symbol: "INPUT_FRONTEND_X",                            label: "Frontend X",                     defaultKey: "Space",       group: "Frontend / UI" },
  { id: 204, symbol: "INPUT_FRONTEND_Y",                            label: "Frontend Y",                     defaultKey: "Tab",         group: "Frontend / UI" },
  { id: 205, symbol: "INPUT_FRONTEND_LB",                           label: "Frontend LB",                    defaultKey: "Q",           group: "Frontend / UI" },
  { id: 206, symbol: "INPUT_FRONTEND_RB",                           label: "Frontend RB",                    defaultKey: "E",           group: "Frontend / UI" },
  { id: 207, symbol: "INPUT_FRONTEND_LT",                           label: "Frontend LT",                    defaultKey: "Page Down",   group: "Frontend / UI" },
  { id: 208, symbol: "INPUT_FRONTEND_RT",                           label: "Frontend RT",                    defaultKey: "Page Up",     group: "Frontend / UI" },
  { id: 209, symbol: "INPUT_FRONTEND_LS",                           label: "Frontend LS",                    defaultKey: "Left Shift",  group: "Frontend / UI" },
  { id: 210, symbol: "INPUT_FRONTEND_RS",                           label: "Frontend RS",                    defaultKey: "Left Ctrl",   group: "Frontend / UI" },
  { id: 211, symbol: "INPUT_FRONTEND_LEADERBOARD",                  label: "Frontend Leaderboard",           defaultKey: "Tab",         group: "Frontend / UI" },
  { id: 212, symbol: "INPUT_FRONTEND_SOCIAL_CLUB",                  label: "Frontend Social Club",           defaultKey: "Home",        group: "Frontend / UI" },
  { id: 214, symbol: "INPUT_FRONTEND_DELETE",                       label: "Frontend Delete",                defaultKey: "Delete",      group: "Frontend / UI" },
  { id: 215, symbol: "INPUT_FRONTEND_ENDSCREEN_ACCEPT",             label: "Frontend Endscreen Accept",      defaultKey: "Enter",       group: "Frontend / UI" },
  { id: 216, symbol: "INPUT_FRONTEND_ENDSCREEN_EXPAND",             label: "Frontend Endscreen Expand",      defaultKey: "Space",       group: "Frontend / UI" },
  { id: 217, symbol: "INPUT_FRONTEND_SELECT",                       label: "Frontend Select",                defaultKey: "Caps Lock",   group: "Frontend / UI" },
  { id: 244, symbol: "INPUT_INTERACTION_MENU",                      label: "Interaction Menu",               defaultKey: "M",           group: "Frontend / UI" },

  // ── Multiplayer ────────────────────────────────────────────────────────────
  { id: 245, symbol: "INPUT_MP_TEXT_CHAT_ALL",                      label: "Chat (All)",                     defaultKey: "T",           group: "Multiplayer" },
  { id: 246, symbol: "INPUT_MP_TEXT_CHAT_TEAM",                     label: "Chat (Team)",                    defaultKey: "Y",           group: "Multiplayer" },
  { id: 247, symbol: "INPUT_MP_TEXT_CHAT_FRIENDS",                  label: "Chat (Friends)",                                            group: "Multiplayer" },
  { id: 248, symbol: "INPUT_MP_TEXT_CHAT_CREW",                     label: "Chat (Crew)",                                               group: "Multiplayer" },
  { id: 249, symbol: "INPUT_PUSH_TO_TALK",                          label: "Push To Talk",                   defaultKey: "N",           group: "Multiplayer" },

  // ── Misc ───────────────────────────────────────────────────────────────────
  { id: 8,   symbol: "INPUT_SCRIPTED_FLY_UD",                       label: "Scripted Fly UD",                defaultKey: "S",           group: "Misc" },
  { id: 9,   symbol: "INPUT_SCRIPTED_FLY_LR",                       label: "Scripted Fly LR",                defaultKey: "D",           group: "Misc" },
  { id: 10,  symbol: "INPUT_SCRIPTED_FLY_ZUP",                      label: "Scripted Fly Zup",               defaultKey: "Page Up",     group: "Misc" },
  { id: 11,  symbol: "INPUT_SCRIPTED_FLY_ZDOWN",                    label: "Scripted Fly Zdown",             defaultKey: "Page Down",   group: "Misc" },
  { id: 16,  symbol: "INPUT_SELECT_NEXT_WEAPON",                    label: "Select Next Weapon",             defaultKey: "Scroll Down", group: "Misc" },
  { id: 17,  symbol: "INPUT_SELECT_PREV_WEAPON",                    label: "Select Prev Weapon",             defaultKey: "Scroll Up",   group: "Misc" },
  { id: 18,  symbol: "INPUT_SKIP_CUTSCENE",                         label: "Skip Cutscene",                  defaultKey: "Enter",       group: "Misc" },
  { id: 19,  symbol: "INPUT_CHARACTER_WHEEL",                       label: "Character Wheel",                defaultKey: "Left Alt",    group: "Misc" },
  { id: 20,  symbol: "INPUT_MULTIPLAYER_INFO",                      label: "Player List",                    defaultKey: "Z",           group: "Misc" },
  { id: 28,  symbol: "INPUT_SPECIAL_ABILITY",                       label: "Special Ability",                                           group: "Misc" },
  { id: 29,  symbol: "INPUT_SPECIAL_ABILITY_SECONDARY",             label: "Special Ability Secondary",      defaultKey: "B",           group: "Misc" },
  { id: 39,  symbol: "INPUT_SNIPER_ZOOM",                           label: "Sniper Zoom",                    defaultKey: "[",           group: "Misc" },
  { id: 40,  symbol: "INPUT_SNIPER_ZOOM_IN_ONLY",                   label: "Sniper Zoom In Only",            defaultKey: "]",           group: "Misc" },
  { id: 41,  symbol: "INPUT_SNIPER_ZOOM_OUT_ONLY",                  label: "Sniper Zoom Out Only",           defaultKey: "[",           group: "Misc" },
  { id: 42,  symbol: "INPUT_SNIPER_ZOOM_IN_SECONDARY",              label: "Sniper Zoom In Secondary",       defaultKey: "]",           group: "Misc" },
  { id: 43,  symbol: "INPUT_SNIPER_ZOOM_OUT_SECONDARY",             label: "Sniper Zoom Out Secondary",      defaultKey: "[",           group: "Misc" },
  { id: 46,  symbol: "INPUT_TALK",                                  label: "Talk",                           defaultKey: "E",           group: "Misc" },
  { id: 48,  symbol: "INPUT_HUD_SPECIAL",                           label: "Special Ability",                defaultKey: "Z",           group: "Misc" },
  { id: 49,  symbol: "INPUT_ARREST",                                label: "Arrest",                         defaultKey: "F",           group: "Misc" },
  { id: 50,  symbol: "INPUT_ACCURATE_AIM",                          label: "Accurate Aim",                   defaultKey: "Scroll Down", group: "Misc" },
  { id: 51,  symbol: "INPUT_CONTEXT",                               label: "Context (E)",                    defaultKey: "E",           group: "Misc" },
  { id: 52,  symbol: "INPUT_CONTEXT_SECONDARY",                     label: "Context Secondary",              defaultKey: "Q",           group: "Misc" },
  { id: 55,  symbol: "INPUT_DIVE",                                  label: "Dive",                           defaultKey: "Space",       group: "Misc" },
  { id: 56,  symbol: "INPUT_DROP_WEAPON",                           label: "Drop Weapon",                    defaultKey: "F9",          group: "Misc" },
  { id: 57,  symbol: "INPUT_DROP_AMMO",                             label: "Drop Ammo",                      defaultKey: "F10",         group: "Misc" },
  { id: 144, symbol: "INPUT_PARACHUTE_DEPLOY",                      label: "Parachute Deploy",               defaultKey: "F",           group: "Misc" },
  { id: 145, symbol: "INPUT_PARACHUTE_DETACH",                      label: "Parachute Detach",               defaultKey: "F",           group: "Misc" },
  { id: 146, symbol: "INPUT_PARACHUTE_TURN_LR",                     label: "Parachute Turn LR",              defaultKey: "D",           group: "Misc" },
  { id: 147, symbol: "INPUT_PARACHUTE_TURN_LEFT_ONLY",              label: "Parachute Turn Left Only",       defaultKey: "A",           group: "Misc" },
  { id: 148, symbol: "INPUT_PARACHUTE_TURN_RIGHT_ONLY",             label: "Parachute Turn Right Only",      defaultKey: "D",           group: "Misc" },
  { id: 149, symbol: "INPUT_PARACHUTE_PITCH_UD",                    label: "Parachute Pitch UD",             defaultKey: "S",           group: "Misc" },
  { id: 150, symbol: "INPUT_PARACHUTE_PITCH_UP_ONLY",               label: "Parachute Pitch Up Only",        defaultKey: "W",           group: "Misc" },
  { id: 151, symbol: "INPUT_PARACHUTE_PITCH_DOWN_ONLY",             label: "Parachute Pitch Down Only",      defaultKey: "S",           group: "Misc" },
  { id: 152, symbol: "INPUT_PARACHUTE_BRAKE_LEFT",                  label: "Parachute Brake Left",           defaultKey: "Q",           group: "Misc" },
  { id: 153, symbol: "INPUT_PARACHUTE_BRAKE_RIGHT",                 label: "Parachute Brake Right",          defaultKey: "E",           group: "Misc" },
  { id: 154, symbol: "INPUT_PARACHUTE_SMOKE",                       label: "Parachute Smoke",                defaultKey: "X",           group: "Misc" },
  { id: 155, symbol: "INPUT_PARACHUTE_PRECISION_LANDING",           label: "Parachute Precision Landing",    defaultKey: "Left Shift",  group: "Misc" },
  { id: 156, symbol: "INPUT_MAP",                                   label: "Map",                                                       group: "Misc" },
  { id: 166, symbol: "INPUT_SELECT_CHARACTER_MICHAEL",              label: "Select Character Michael",       defaultKey: "F5",          group: "Misc" },
  { id: 167, symbol: "INPUT_SELECT_CHARACTER_FRANKLIN",             label: "Select Character Franklin",      defaultKey: "F6",          group: "Misc" },
  { id: 168, symbol: "INPUT_SELECT_CHARACTER_TREVOR",               label: "Select Character Trevor",        defaultKey: "F7",          group: "Misc" },
  { id: 169, symbol: "INPUT_SELECT_CHARACTER_MULTIPLAYER",          label: "Select Character Multiplayer",   defaultKey: "F8",          group: "Misc" },
  { id: 170, symbol: "INPUT_SAVE_REPLAY_CLIP",                      label: "Save Replay Clip",               defaultKey: "F3",          group: "Misc" },
  { id: 171, symbol: "INPUT_SPECIAL_ABILITY_PC",                    label: "Special Ability Pc",             defaultKey: "Caps Lock",   group: "Misc" },
  { id: 218, symbol: "INPUT_SCRIPT_LEFT_AXIS_X",                    label: "Script Left Axis X",             defaultKey: "D",           group: "Misc" },
  { id: 219, symbol: "INPUT_SCRIPT_LEFT_AXIS_Y",                    label: "Script Left Axis Y",             defaultKey: "S",           group: "Misc" },
  { id: 220, symbol: "INPUT_SCRIPT_RIGHT_AXIS_X",                   label: "Script Right Axis X",            defaultKey: "Mouse X",     group: "Misc" },
  { id: 221, symbol: "INPUT_SCRIPT_RIGHT_AXIS_Y",                   label: "Script Right Axis Y",            defaultKey: "Mouse Y",     group: "Misc" },
  { id: 222, symbol: "INPUT_SCRIPT_RUP",                            label: "Script Rup",                     defaultKey: "Mouse 2",     group: "Misc" },
  { id: 223, symbol: "INPUT_SCRIPT_RDOWN",                          label: "Script Rdown",                   defaultKey: "Mouse 1",     group: "Misc" },
  { id: 224, symbol: "INPUT_SCRIPT_RLEFT",                          label: "Script Rleft",                   defaultKey: "Left Ctrl",   group: "Misc" },
  { id: 225, symbol: "INPUT_SCRIPT_RRIGHT",                         label: "Script Rright",                  defaultKey: "Mouse 2",     group: "Misc" },
  { id: 226, symbol: "INPUT_SCRIPT_LB",                             label: "Script LB",                                                 group: "Misc" },
  { id: 227, symbol: "INPUT_SCRIPT_RB",                             label: "Script RB",                                                 group: "Misc" },
  { id: 228, symbol: "INPUT_SCRIPT_LT",                             label: "Script LT",                                                 group: "Misc" },
  { id: 229, symbol: "INPUT_SCRIPT_RT",                             label: "Script RT",                      defaultKey: "Mouse 1",     group: "Misc" },
  { id: 230, symbol: "INPUT_SCRIPT_LS",                             label: "Script LS",                                                 group: "Misc" },
  { id: 231, symbol: "INPUT_SCRIPT_RS",                             label: "Script RS",                                                 group: "Misc" },
  { id: 232, symbol: "INPUT_SCRIPT_PAD_UP",                         label: "Script Pad Up",                  defaultKey: "W",           group: "Misc" },
  { id: 233, symbol: "INPUT_SCRIPT_PAD_DOWN",                       label: "Script Pad Down",                defaultKey: "S",           group: "Misc" },
  { id: 234, symbol: "INPUT_SCRIPT_PAD_LEFT",                       label: "Script Pad Left",                defaultKey: "A",           group: "Misc" },
  { id: 235, symbol: "INPUT_SCRIPT_PAD_RIGHT",                      label: "Script Pad Right",               defaultKey: "D",           group: "Misc" },
  { id: 236, symbol: "INPUT_SCRIPT_SELECT",                         label: "Script Select",                  defaultKey: "V",           group: "Misc" },
  { id: 237, symbol: "INPUT_CURSOR_ACCEPT",                         label: "Cursor Accept",                  defaultKey: "Mouse 1",     group: "Misc" },
  { id: 238, symbol: "INPUT_CURSOR_CANCEL",                         label: "Cursor Cancel",                  defaultKey: "Mouse 2",     group: "Misc" },
  { id: 239, symbol: "INPUT_CURSOR_X",                              label: "Cursor X",                                                  group: "Misc" },
  { id: 240, symbol: "INPUT_CURSOR_Y",                              label: "Cursor Y",                                                  group: "Misc" },
  { id: 241, symbol: "INPUT_CURSOR_SCROLL_UP",                      label: "Cursor Scroll Up",               defaultKey: "Scroll Up",   group: "Misc" },
  { id: 242, symbol: "INPUT_CURSOR_SCROLL_DOWN",                    label: "Cursor Scroll Down",             defaultKey: "Scroll Down", group: "Misc" },
  { id: 243, symbol: "INPUT_ENTER_CHEAT_CODE",                      label: "Enter Cheat Code",               defaultKey: "~",           group: "Misc" },
  { id: 250, symbol: "INPUT_CREATOR_LS",                            label: "Creator LS",                     defaultKey: "R",           group: "Misc" },
  { id: 251, symbol: "INPUT_CREATOR_RS",                            label: "Creator RS",                     defaultKey: "F",           group: "Misc" },
  { id: 252, symbol: "INPUT_CREATOR_LT",                            label: "Creator LT",                     defaultKey: "X",           group: "Misc" },
  { id: 253, symbol: "INPUT_CREATOR_RT",                            label: "Creator RT",                     defaultKey: "C",           group: "Misc" },
  { id: 254, symbol: "INPUT_CREATOR_MENU_TOGGLE",                   label: "Creator Menu Toggle",            defaultKey: "Left Shift",  group: "Misc" },
  { id: 255, symbol: "INPUT_CREATOR_ACCEPT",                        label: "Creator Accept",                 defaultKey: "Space",       group: "Misc" },
  { id: 256, symbol: "INPUT_CREATOR_DELETE",                        label: "Creator Delete",                 defaultKey: "Delete",      group: "Misc" },
  { id: 258, symbol: "INPUT_RAPPEL_JUMP",                           label: "Rappel Jump",                                               group: "Misc" },
  { id: 259, symbol: "INPUT_RAPPEL_LONG_JUMP",                      label: "Rappel Long Jump",                                          group: "Misc" },
  { id: 260, symbol: "INPUT_RAPPEL_SMASH_WINDOW",                   label: "Rappel Smash Window",                                       group: "Misc" },
  { id: 261, symbol: "INPUT_PREV_WEAPON",                           label: "Prev Weapon",                    defaultKey: "Scroll Up",   group: "Misc" },
  { id: 262, symbol: "INPUT_NEXT_WEAPON",                           label: "Next Weapon",                    defaultKey: "Scroll Down", group: "Misc" },
  { id: 265, symbol: "INPUT_WHISTLE",                               label: "Whistle",                                                   group: "Misc" },
  { id: 274, symbol: "INPUT_SNIPER_ZOOM_IN",                        label: "Sniper Zoom In",                 defaultKey: "[",           group: "Misc" },
  { id: 275, symbol: "INPUT_SNIPER_ZOOM_OUT",                       label: "Sniper Zoom Out",                defaultKey: "[",           group: "Misc" },
  { id: 276, symbol: "INPUT_SNIPER_ZOOM_IN_ALTERNATE",              label: "Sniper Zoom In Alternate",       defaultKey: "[",           group: "Misc" },
  { id: 277, symbol: "INPUT_SNIPER_ZOOM_OUT_ALTERNATE",             label: "Sniper Zoom Out Alternate",      defaultKey: "[",           group: "Misc" },
  { id: 288, symbol: "INPUT_REPLAY_START_STOP_RECORDING",           label: "Replay Record",                  defaultKey: "F1",          group: "Misc" },
  { id: 289, symbol: "INPUT_REPLAY_START_STOP_RECORDING_SECONDARY", label: "Replay Record (alt)",            defaultKey: "F2",          group: "Misc" },
  { id: 290, symbol: "INPUT_SCALED_LOOK_LR",                        label: "Scaled Look LR",                 defaultKey: "Mouse X",     group: "Misc" },
  { id: 291, symbol: "INPUT_SCALED_LOOK_UD",                        label: "Scaled Look UD",                 defaultKey: "Mouse Y",     group: "Misc" },
  { id: 292, symbol: "INPUT_SCALED_LOOK_UP_ONLY",                   label: "Scaled Look Up Only",                                       group: "Misc" },
  { id: 293, symbol: "INPUT_SCALED_LOOK_DOWN_ONLY",                 label: "Scaled Look Down Only",                                     group: "Misc" },
  { id: 294, symbol: "INPUT_SCALED_LOOK_LEFT_ONLY",                 label: "Scaled Look Left Only",                                     group: "Misc" },
  { id: 295, symbol: "INPUT_SCALED_LOOK_RIGHT_ONLY",                label: "Scaled Look Right Only",                                    group: "Misc" },
  { id: 296, symbol: "INPUT_REPLAY_MARKER_DELETE",                  label: "Replay Marker Delete",           defaultKey: "Delete",      group: "Misc" },
  { id: 297, symbol: "INPUT_REPLAY_CLIP_DELETE",                    label: "Replay Clip Delete",             defaultKey: "Delete",      group: "Misc" },
  { id: 298, symbol: "INPUT_REPLAY_PAUSE",                          label: "Replay Pause",                   defaultKey: "Space",       group: "Misc" },
  { id: 299, symbol: "INPUT_REPLAY_REWIND",                         label: "Replay Rewind",                  defaultKey: "Down Arrow",  group: "Misc" },
  { id: 300, symbol: "INPUT_REPLAY_FFWD",                           label: "Replay Ffwd",                    defaultKey: "Up Arrow",    group: "Misc" },
  { id: 301, symbol: "INPUT_REPLAY_NEWMARKER",                      label: "Replay Newmarker",               defaultKey: "M",           group: "Misc" },
  { id: 302, symbol: "INPUT_REPLAY_RECORD",                         label: "Replay Record",                  defaultKey: "S",           group: "Misc" },
  { id: 303, symbol: "INPUT_REPLAY_SCREENSHOT",                     label: "Replay Screenshot",              defaultKey: "U",           group: "Misc" },
  { id: 304, symbol: "INPUT_REPLAY_HIDEHUD",                        label: "Replay Hidehud",                 defaultKey: "H",           group: "Misc" },
  { id: 305, symbol: "INPUT_REPLAY_STARTPOINT",                     label: "Replay Startpoint",              defaultKey: "B",           group: "Misc" },
  { id: 306, symbol: "INPUT_REPLAY_ENDPOINT",                       label: "Replay Endpoint",                defaultKey: "N",           group: "Misc" },
  { id: 307, symbol: "INPUT_REPLAY_ADVANCE",                        label: "Replay Advance",                 defaultKey: "Right Arrow", group: "Misc" },
  { id: 308, symbol: "INPUT_REPLAY_BACK",                           label: "Replay Back",                    defaultKey: "Left Arrow",  group: "Misc" },
  { id: 309, symbol: "INPUT_REPLAY_TOOLS",                          label: "Replay Tools",                   defaultKey: "T",           group: "Misc" },
  { id: 310, symbol: "INPUT_REPLAY_RESTART",                        label: "Replay Restart",                 defaultKey: "R",           group: "Misc" },
  { id: 311, symbol: "INPUT_REPLAY_SHOWHOTKEY",                     label: "Replay Showhotkey",              defaultKey: "K",           group: "Misc" },
  { id: 312, symbol: "INPUT_REPLAY_CYCLEMARKERLEFT",                label: "Replay Cyclemarkerleft",         defaultKey: "[",           group: "Misc" },
  { id: 313, symbol: "INPUT_REPLAY_CYCLEMARKERRIGHT",               label: "Replay Cyclemarkerright",        defaultKey: "]",           group: "Misc" },
  { id: 314, symbol: "INPUT_REPLAY_FOVINCREASE",                    label: "Replay Fovincrease",             defaultKey: "Numpad +",    group: "Misc" },
  { id: 315, symbol: "INPUT_REPLAY_FOVDECREASE",                    label: "Replay Fovdecrease",             defaultKey: "Numpad -",    group: "Misc" },
  { id: 318, symbol: "INPUT_REPLAY_SAVE",                           label: "Replay Save",                    defaultKey: "F5",          group: "Misc" },
  { id: 319, symbol: "INPUT_REPLAY_TOGGLETIME",                     label: "Replay Toggletime",              defaultKey: "C",           group: "Misc" },
  { id: 320, symbol: "INPUT_REPLAY_TOGGLETIPS",                     label: "Replay Toggletips",              defaultKey: "V",           group: "Misc" },
  { id: 321, symbol: "INPUT_REPLAY_PREVIEW",                        label: "Replay Preview",                 defaultKey: "Space",       group: "Misc" },
  { id: 322, symbol: "INPUT_REPLAY_TOGGLE_TIMELINE",                label: "Replay Toggle Timeline",         defaultKey: "Esc",         group: "Misc" },
  { id: 323, symbol: "INPUT_REPLAY_TIMELINE_PICKUP_CLIP",           label: "Replay Timeline Pickup Clip",    defaultKey: "X",           group: "Misc" },
  { id: 324, symbol: "INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP",        label: "Replay Timeline Duplicate Clip", defaultKey: "C",           group: "Misc" },
  { id: 325, symbol: "INPUT_REPLAY_TIMELINE_PLACE_CLIP",            label: "Replay Timeline Place Clip",     defaultKey: "V",           group: "Misc" },
  { id: 326, symbol: "INPUT_REPLAY_CTRL",                           label: "Replay Ctrl",                    defaultKey: "Left Ctrl",   group: "Misc" },
  { id: 327, symbol: "INPUT_REPLAY_TIMELINE_SAVE",                  label: "Replay Timeline Save",           defaultKey: "F5",          group: "Misc" },
  { id: 328, symbol: "INPUT_REPLAY_PREVIEW_AUDIO",                  label: "Replay Preview Audio",           defaultKey: "Space",       group: "Misc" },
  { id: 332, symbol: "INPUT_RADIO_WHEEL_UD",                        label: "Radio Wheel UD",                 defaultKey: "Mouse Y",     group: "Misc" },
  { id: 333, symbol: "INPUT_RADIO_WHEEL_LR",                        label: "Radio Wheel LR",                 defaultKey: "Mouse X",     group: "Misc" },
  { id: 344, symbol: "INPUT_SWITCH_VISOR",                          label: "Switch Visor",                   defaultKey: "F11",         group: "Misc" },
  { id: 348, symbol: "INPUT_MAP_POI",                               label: "Map Poi",                        defaultKey: "Mouse 3",     group: "Misc" },
  { id: 349, symbol: "INPUT_REPLAY_SNAPMATIC_PHOTO",                label: "Replay Snapmatic Photo",         defaultKey: "Tab",         group: "Misc" },
  { id: 358, symbol: "INPUT_QUAD_LOCO_REVERSE",                     label: "Quad Loco Reverse",                                         group: "Misc" },
  { id: 359, symbol: "INPUT_RESPAWN_FASTER",                        label: "Respawn Faster",                                            group: "Misc" },
  { id: 360, symbol: "INPUT_HUDMARKER_SELECT",                      label: "Hudmarker Select",                                          group: "Misc" },
];

const BY_ID = new Map<number, GtaControl>(GTA_CONTROLS.map((c) => [c.id, c]));

export function getGtaControl(id: number): GtaControl | undefined {
  return BY_ID.get(id);
}

/** Format a control id as `Label (id)`, falling back to `Control id` if unknown. */
export function formatGtaControl(id: number): string {
  const c = BY_ID.get(id);
  if (!c) return `Control ${id}`;
  return c.defaultKey ? `${c.label} (${id} · ${c.defaultKey})` : `${c.label} (${id})`;
}

/** Group order used by ControlSelect / ControlMultiSelect for the dropdown headings. */
export const GTA_CONTROL_GROUP_ORDER: GtaControlGroup[] = [
  "Camera",
  "Movement",
  "Combat",
  "Cover",
  "Vehicle",
  "Vehicle (Plane/Heli)",
  "Vehicle (Boat/Bike)",
  "Phone",
  "Frontend / UI",
  "Multiplayer",
  "Misc",
];
